"""empty message

Revision ID: 577a1001cf6f
Revises: 67a43b128af5
Create Date: 2019-06-23 12:39:07.678431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577a1001cf6f'
down_revision = '67a43b128af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_card_token', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('stripe_subscription_id', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'users', ['stripe_subscription_id'])
    op.create_unique_constraint(None, 'users', ['stripe_card_token'])
    op.create_unique_constraint(None, 'users', ['stripe_customer_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'stripe_subscription_id')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'stripe_card_token')
    # ### end Alembic commands ###
