"""empty message

Revision ID: 67a43b128af5
Revises: 67fc1a42a4e2
Create Date: 2019-06-21 12:18:51.769617

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy import Column
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = '67a43b128af5'
down_revision = '67fc1a42a4e2'
branch_labels = None
depends_on = None


def upgrade():
    enum = ENUM("free", "trial", "monthly", "yearly", name="plan_enum", create_type=False)
    enum.create(op.get_bind(), checkfirst=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users',
                  sa.Column('plan', enum, server_default='free', nullable=False))

    op.add_column('users', sa.Column('plan_expiration', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan_expiration')
    op.drop_column('users', 'plan')
    # ### end Alembic commands ###

